
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fernando Gonzalez
 */
public class jfrmCompu extends javax.swing.JFrame {

    /**
     * Creates new form jfrmCompu
     */
    public jfrmCompu() {
        initComponents();
        this.setTitle("Partes de una PC");
        this.setLocationRelativeTo(null);
        this.setSize(600, 400);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblPieza = new javax.swing.JLabel();
        jlblContenido = new javax.swing.JLabel();
        jlblFuncion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jlblNomPieza.setText("jLabel1");

        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\2.jfif")); // NOI18N

        jlblContenido.setText("jLabel1");

        jlblFuncion.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jlblNomPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlblPieza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblContenido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblFuncion)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblNomPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblContenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblFuncion)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setMnemonic('a');
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('g');
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setMnemonic('s');
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componente de PC");

        jMenuItem4.setText("Motherboard");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria RAM");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Disco Duro (HDD)");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Unidad SSD");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Fuente de Poder ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Tarjeta de Video (GPU)");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Red");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Cooler del Procesador");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Ventilador del Gabinete");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Tarjeta de Sonido");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Batería CMOS");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Cable SATA");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Cable de Alimentación");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("BIOS / UEFI");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem19.setText("Acerca del programa");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Créditos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad de Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad de Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int msg=JOptionPane.showConfirmDialog(null, "Desea Salir Del Programa");
        if(msg==0)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Cooler del Procesador");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\09.jpg"));
        jlblContenido.setText("Es un sistema de enfriamiento compuesto por un disipador y un ventilador.");
        jlblFuncion.setText("Mantener la temperatura del procesador en niveles seguros.");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Ventilador del Gabinete");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\010.jpg"));
        jlblContenido.setText("Es un ventilador instalado dentro del gabinete de la computadora.");
        jlblFuncion.setText("Mejorar la circulación del aire y enfriar los componentes internos.");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:jlblPieza.setText("");
        jlblPieza.setText("");
        jlblNomPieza.setText("Motherboard");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\01.jpg"));
        jlblContenido.setText("Es la tarjeta principal donde se conectan todos los componentes de la computadora.");
        jlblFuncion.setText("Permitir la comunicación y conexión entre todos los componentes del equipo.");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Procesador");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\02.jpg"));
        jlblContenido.setText("Es el cerebro de la computadora que ejecuta instrucciones y realiza cálculos.");
        jlblFuncion.setText("Procesar datos y controlar el funcionamiento de todo el sistema.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Memoria RAM");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\03.jpg"));
        jlblContenido.setText("Es una memoria temporal donde se almacenan los datos de los programas en uso.");
        jlblFuncion.setText("Permitir un acceso rápido a la información mientras la computadora está funcionando.");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Disco Duro (HDD)");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\04.jpg"));
        jlblContenido.setText("Es un dispositivo de almacenamiento que utiliza discos magnéticos para guardar información.");
        jlblFuncion.setText("Almacenar el sistema operativo, programas y archivos de forma permanente.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Unidad SSD");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\05.jpg"));
        jlblContenido.setText("Es un dispositivo de almacenamiento que utiliza memoria flash, sin partes móviles.");
        jlblFuncion.setText("Guardar datos de manera permanente con mayor velocidad que un HDD.");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Fuente de Poder");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\06.jpg"));
        jlblContenido.setText("Es el componente que convierte la corriente eléctrica en energía adecuada para la computadora.");
        jlblFuncion.setText("Suministrar energía eléctrica a todos los componentes del equipo.");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Tarjeta de Video (GPU) ");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\07.jpg"));
        jlblContenido.setText("Es un componente encargado de procesar los gráficos e imágenes.");
        jlblFuncion.setText("Generar y mostrar imágenes, videos y gráficos en el monitor.");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Tarjeta de Red");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\08.jpg"));
        jlblContenido.setText("Es un dispositivo que permite la conexión de la computadora a una red o a Internet.");
        jlblFuncion.setText("Enviar y recibir datos a través de una red.");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Tarjeta de Sonido");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\011.jpg"));
        jlblContenido.setText("Es un componente que procesa las señales de audio.");
        jlblFuncion.setText("Permitir la reproducción y grabación de sonido.");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Batería CMOS");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\012.jpg"));
        jlblContenido.setText("Es una pequeña batería instalada en la placa madre.");
        jlblFuncion.setText("Mantener la configuración del BIOS/UEFI y el reloj del sistema cuando la computadora está apagada.");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Cable SATA ");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\013.jpg"));
        jlblContenido.setText("Es un cable utilizado para transmitir datos entre la placa madre y dispositivos de almacenamiento.");
        jlblFuncion.setText("Transferir datos entre el HDD o SSD y la motherboard.");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("Cable de Alimentación");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\014.jpg"));
        jlblContenido.setText("Es un cable que suministra energía desde la fuente de poder a los componentes internos.");
        jlblFuncion.setText("Proporcionar energía eléctrica a discos, placa madre y otros dispositivos.");
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblPieza.setText("");
        jlblNomPieza.setText("BIOS / UEFI");
        jlblPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fernando Gonzalez\\Documents\\NetBeansProjects\\Guia3_AllanGonzalez_IVD_14\\src\\imagenes\\015.jpg"));
        jlblContenido.setText("Es el firmware que inicia la computadora y configura el hardware antes de cargar el sistema operativo.");
        jlblFuncion.setText("Verificar el hardware al encender el equipo e iniciar el sistema operativo.");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
            "Este programa fue desarrollado para mostrar información sobre los principales "
            + "componentes internos de una computadora. Su funcionamiento consiste en presentar "
            + "el concepto y la función principal de cada componente, permitiendo al usuario "
            + "conocer la importancia de la motherboard, el procesador, la memoria RAM, el disco "
            + "duro, la unidad SSD, la fuente de poder, la tarjeta de video, la tarjeta de red, "
            + "el sistema de enfriamiento, la tarjeta de sonido, la batería CMOS, los cables "
            + "SATA y de alimentación, así como el BIOS/UEFI. De esta manera, el programa sirve "
            + "como una herramienta educativa para comprender cómo trabajan en conjunto los "
            + "componentes de una computadora.",
            "Acerca del Programa",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Allan Fernando Federico Gonzalez Flores-IVD-14-Computacion-Eliezer Crup");
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCompu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCompu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCompu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCompu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCompu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblContenido;
    private javax.swing.JLabel jlblFuncion;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPieza;
    // End of variables declaration//GEN-END:variables
}
